Our Controller will call a service that calculates the average grade of all students. When we run the application, the functionality
 of the method will execute fully. However, in a unit test we often want to mock out the service call and only validate
 that it was invoked. Let's first create the service class:

 [source, bash]
 ----
 > grails create-service Student
 ----

*_Before continuing please delete src/test/groovy/grails/controller/testing/StudentServiceSpec.groovy_*

[source, groovy]
.grails-app/services/grails/controller/testing/StudentService.groovy
----
include::{sourceDir}/grails-app/services/grails/controller/testing/StudentService.groovy[indent=0]
----

In `StudentController` we will inject the `StudentService` and create an action which delegates to the service:

[source, groovy]
.grails-app/controllers/grails/controller/testing/StudentController.groovy
----
include::{sourceDir}/grails-app/controllers/grails/controller/testing/StudentController.groovy[tags=injectedStudentService]
include::{sourceDir}/grails-app/controllers/grails/controller/testing/StudentController.groovy[tags=calculateAvgGradeMethod]
----

In `StudentControllerSpec` we need to mock the service and inject it into the controller. We also validate that the service
method is being executed once and will return `100`. Use the `response` property to assert the returning text.

[source, groovy]
.src/test/groovy/grails/controller/testing/StudentControllerSpec.groovy
----
    //...
    def setup() {
        controller.studentService = Mock(StudentService)
    }
    //...
    void "Test controller correctly calls service method"() {
        when: "controller is invoked to calculate grades"
            controller.calculateAvgGrade()

        then: "verify the service was called and response received"
            response.text == "Avg Grade is 100"
            1 * controller.studentService.calculateAvgGrade() >> 100
    }
----