[big]*Validate View and Response Redirect on Save*

The `save()` action method checks for `null` or errors, saves a student, then proceeds to return a student back to the model.
It also redirects the student to the `show.gsp` page.

[source, groovy]
.grails-app/controllers/demo/StudentController.groovy
----
include::{sourceDir}/grails-app/controllers/demo/StudentController.groovy[tags=saveMethod]
----

In the Spec, we must provide params to the domain object `Student` to allow it to save. Add to the `populateValidParams`
method appropriately. Also notice in the Spec how we can manipulate the `contentType`, the `request` method with `POST`,
and access the `redirectedUrl` property in the `response`:

[source, groovy]
.sample code snippets
----
request.contentType = FORM_CONTENT_TYPE
request.method = 'POST'
response.redirectedUrl == '/student/show/1'
----

Your resulting code should resemble below:

[source, groovy]
.src/test/groovy/demo/StudentControllerSpec.groovy
----
include::{sourceDir}/src/version-code/StudentControllerSpec.groovy_v1[indent=0]
----

<1> Since the save method is restricted to `POST`, we must specify the request.method is a `POST` call
<2> Validate the redirectedUrl

[big]*Edit, Delete, Update, Show Actions*

Take a look at the entire `StudentControllerSpec` that was generated and observe the rest of the tests. They also make use of the
`controller, model, request, response, and view` properties to validate the functionality of the actions.
